log_file = /var/log/auditd/auditd.log
log_format = RAW
log_group = 9
flush = sync
max_log_file = 100
max_log_file_action = keep_logs
space_left = 10
space_left_action = halt
admin_space_left = 5
admin_space_left_action = halt
disk_full_action = halt
disk_error_action = halt
